version: '3.5'

services:
    mongo:
        image: mongors:test
        environment:
            - MONGO_INITDB_ROOT_USERNAME=test
            - MONGO_INITDB_ROOT_PASSWORD=secure
            - MONGODB_REPLICA_SET_NAME=replica1
            - MONGO_HOSTNAME=localhost
            - MONGODB_PORT=27017
        ports:
          - "27017:27017"
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=test
            - ME_CONFIG_MONGODB_ADMINPASSWORD=secure
            - ME_CONFIG_MONGODB_URL=mongodb://test:secure@mongo:27017/
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
        depends_on:
            - mongo
        ports:
          - "8888:8081"
